AllCops:
  Exclude:
    - 'ruby_isds.gemspec'
    - 'spec/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 98

Style/Documentation:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false
